apiVersion: v1
kind: ConfigMap
metadata:
  name: v2ray-config
data:
  config.json: |-
    {
      "log": {
        "access": "none"
      },
      "inbounds": [
        {
          "port": 8080,
          "protocol": "vmess",
          "settings": {
            "decryption": "none",
            "clients": [
              {
                "id": "18ad2c9c-a88b-48e8-aa64-5dee0045c282"
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
              "path": "ws"
            }
          }
        },
        {
          "port": 8080,
          "protocol": "vmess",
          "settings": {
            "decryption": "none",
            "clients": [
              {
                "id": "18ad2c9c-a88b-48e8-aa64-5dee0045c282"
              }
            ]
          },
          "streamSettings": {
            "network": "mkcp",
            "kcpSettings": {
              "uplinkCapacity": 5,
              "downlinkCapacity": 100,
              "congestion": true,
              "header": {
                "type": "wechat-video"
              }
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-deployment
spec:
  selector:
    matchLabels:
      app: v2ray
  replicas: 1
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
      - name: v2ray
        image: zhu327/v2ray
        ports:
          - containerPort: 8080
            name: tcp
          - containerPort: 8080
            protocol: UDP
            name: udp
        env:
        - name: CONFIG_JSON
          valueFrom:
            configMapKeyRef:
              name: v2ray-config
              key: config.json
      - name: tunnel
        image: cloudflare/cloudflared:2021.9.2
        command: ["cloudflared", "tunnel", "--no-autoupdate=true"]
---
apiVersion: v1
kind: Service
metadata:
  name: v2ray-service
spec:
  selector:
    app: v2ray
  type: NodePort
  ports:
    - name: udp
      protocol: UDP
      port: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp2raw-deployment
spec:
  selector:
    matchLabels:
      app: udp2raw
  replicas: 1
  template:
    metadata:
      labels:
        app: udp2raw
    spec:
      hostNetwork: true
      containers:
        - name: udp2raw
          image: jasperhale/udp2raw
          securityContext:
            privileged: true
          command:
            - ./udp2raw
          args:
            - '-s'
            - '-l'
            - '0.0.0.0:900'
            - '-r'
            - '$(V2RAY_SERVICE_SERVICE_HOST):$(V2RAY_SERVICE_SERVICE_PORT_UDP)'
            - '-k'
            - password
            - '--cipher-mode'
            - xor
            - '--auth-mode'
            - simple
            - '--raw-mode'
            - icmp
            - '--seq-mode'
            - '3'
            - '-a'
            - '--keep-rule'
            - '--sock-buf'
            - '10240'
